version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./prisma/db:/usr/src/app/prisma/db
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3001}
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

volumes:
  sqlite-db:
