services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./prisma/db:/usr/src/app/prisma/db
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3001}
    restart: always

volumes:
  sqlite_data:

  