services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - ./prisma/db:/usr/src/app/prisma/db    # Persist SQLite database file only
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3001}
    restart: always
